# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42dfbc858a7d2c1f9619bfa56906e4d16fbe8edbc0c431a4c81a937469cb204f6075744baba94d32ad5af6e818aa0c75f4889ee80fa743b3de7584a7f26385b

test:
  secret_key_base: ffea8bb07e5c15ef77b276b512ee8ad225a35972ebe4d80dc880b2116b2d219bacba10ab0a3762b835b1f9efb56a32ecdf6eb21eec084682c5af1d4f3ce8d30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
